stages:
  run-snakemake:
    cmd: calkit xenv -n main -- snakemake
    deps:
      - scripts
      - data
      - Snakefile
      - environment.yaml
    outs:
      - mapped_reads
      - calls:
          cache: false
      - sorted_reads
      - plots:
          cache: false
